void gpio_init();
void gpio_read(uint8_t *gpio_val);
void gpio_write(uint8_t gpio_val);
uint8_t gpio_read_sw1();
void gpio_flash_green_led();
void gpio_flash_red_led();
void gpio_flash_leds();
void gpio_red_led_on();
void gpio_red_led_off();
void gpio_green_led_on();
void gpio_green_led_off();
void gpio_disco_led_init();
void gpio_disco_red_led_on();
void gpio_disco_red_led_off();
void gpio_disco_green_led_on();
void gpio_disco_green_led_off();
void gpio_disco_flash_red_led();
void gpio_disco_flash_green_led();